#
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements. See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership. The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License. You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied. See the License for the
# specific language governing permissions and limitations
# under the License.
#

variable "name_prefix" {
  description = "Prefix applied to every secret and parameter name."
  type        = string
}

variable "db_password" {
  description = "Database master password, generated by the caller because the database is created with it."
  type        = string
  sensitive   = true
}

variable "kms_key_id" {
  description = "Customer managed KMS key for the secrets. Defaults to the AWS managed key when null."
  type        = string
  default     = null
}

variable "recovery_window_in_days" {
  description = "Secrets Manager recovery window. Set to 0 to allow immediate re-creation in throwaway environments."
  type        = number
  default     = 7
}

variable "parameters" {
  description = "Non-secret configuration entries written to SSM Parameter Store, keyed by parameter path suffix."
  type        = map(string)
  default     = {}
}

variable "tags" {
  description = "Tags applied to every resource."
  type        = map(string)
  default     = {}
}
